name: Upload Python Package

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*'
  workflow_dispatch:
    inputs:
      target:
        description: 'Target repository (testpypi or pypi)'
        required: true
        default: 'testpypi'
        type: choice
        options:
          - testpypi
          - pypi

permissions:
  contents: read

jobs:
  make_wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Get version (using TAG)
        if: (github.event_name == 'push')
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION_TAG=$VERSION" >> $GITHUB_ENV

      - name: Get version (manual)
        if: (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'testpypi')
        id: get_version_manual
        run: |
          VERSION="0.0.1"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION_TAG=$VERSION" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          echo "FULL_VERSION=$VERSION.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          
      - name: Update version in __init__.py
        run: |
          echo "Version: $VERSION_TAG"
          sed -i "s/__version__ = \"0.1.1\"/__version__ = \"$VERSION_TAG\"/" orsa/__init__.py

      - name: Build distributions
        run: |
          python -m pip install build twine
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: make_wheel
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - make_wheel
    permissions:
      id-token: write

    environment:
      name: pypi

    steps:
      - name: Retrieve WHEEL distributions
        uses: actions/download-artifact@v4
        with:
          name: make_wheel
          path: dist/

      - name: Publish distributions to PyPI
        if: (github.event_name == 'push' || github.event.inputs.target == 'pypi')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          repository-url: https://upload.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Publish distributions to TestPyPI
        if: (github.event.inputs.target == 'testpypi')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          repository-url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
